hyprland-community/hyprland-autoname-workspaces

src/main.rs
=> add on option for case-insensitive matching

src/main.rs
ignore xwayland chromium tooltip popups windows
=> ignore empty class

Cargo.toml
the time version 0.3.1 is release
=> chore: use hyprland-rs git master

Cargo.lock, README.md, src/config/mod.rs, src/renamer/mod.rs
you can now use a "title"
```
[exclude]
"Steam" = "Friends list"
```
=> feat: you can now exclude based on window title

Cargo.lock, README.md, src/config/mod.rs, src/renamer/mod.rs
You can now match on title with `[title.classname]` with `"a word in the title" = "icons"`.
Example:
```
...
[title.kitty]
neomutt = "neomutt"
```
superseed #23
=> feat: use title icon if available in priority

src/renamer/mod.rs
a little refactoring of title handling
=> refactor: shorter way to express the same thing

Cargo.lock, Cargo.toml, README.md, src/config/mod.rs, src/renamer/mod.rs
This PR add the support for the regex and fix #30
=> feat: add regex support

Cargo.lock, Cargo.toml, README.md, src/config/mod.rs, src/renamer/mod.rs
=> feat: allow class and title placeholder in values

Cargo.lock, Cargo.toml, README.md, src/params/mod.rs, src/renamer/mod.rs
Add duplicate counter as ask here https://github.com/cyrinux/hyprland-autoname-workspaces/issues/37
This add a new param `--counter`.
To be test  like this: `cargo r -- --dedup --counter`.
=> feat: add duplicate counter

README.md, contrib/generate_icons.py
This contrib scripts will help you to generate an `[icons]` list from the font awesome yaml file.
=> feat: add fontawesome icons generator helper

.github/workflows/coverage.yml, .gitignore, Cargo.lock, Cargo.toml, Makefile, README.md, src/config/mod.rs, src/main.rs, src/params/mod.rs, src/renamer/formatter.rs, src/renamer/icon.rs, src/renamer/macros.rs, src/renamer/mod.rs
* Big refactoring, thanks to Maximbaz
* Fix support of active state
* Remove useless trailing delim
* Add support of `--config` param by James Coulson <git@coulson.ie>
Co-authored-by: git@maximbaz.com
Co-authored-by: James Coulson <git@coulson.ie>
=> chore: allow only one instance running

.github/ISSUE_TEMPLATE/bug_report.md, Cargo.lock, Cargo.toml, Makefile, README.md, config.toml.example, contrib/generate_icons.py, src/config/mod.rs, src/renamer/formatter.rs, src/renamer/icon.rs, src/renamer/mod.rs
- Add a new test for `AppWorkspace::new` in `formatter.rs`
=> test: Refactor test suite for `AppWorkspace` initialization in `formatters

src/config/mod.rs, src/renamer/formatter.rs, src/renamer/icon.rs, src/renamer/mod.rs
=> chore: refacto, remove a macro

Cargo.lock, src/renamer/mod.rs
help: https://github.com/hyprland-community/hyprland-autoname-workspaces/issues/69
require:
* https://github.com/hyprwm/Hyprland/pull/2419
* https://github.com/hyprland-community/hyprland-rs/pull/56
=> feat: refresh on title update

Cargo.lock, src/renamer/mod.rs
=> fix: dont filter anymore empty class

src/renamer/mod.rs
=> chore: remove a clone

Cargo.lock, Cargo.toml, config.toml.example, src/config/mod.rs
- chore: update libs
- chore: release 1.1.6
=> chore: update libs

README.md
=> docs: link aur package

README.md
=> docs: add nix package

README.md, src/config/mod.rs, src/renamer/formatter.rs
Allow to filter the number of clients to display
https://github.com/hyprland-community/hyprland-autoname-workspaces/issues/105
=> feat: add a new max_clients config param (wip)

src/renamer/icon.rs, src/renamer/mod.rs
Strictly a formatting update. I forgot to run `make lint` on the last couple PRs. Will add that to the checks at some point.
Please delete options that are not relevant.
Existing tests cover it.
=> fix: bad formatting
